задачи 1_1-1_5
js-tasks-ru/jsbasic-20210906-2_s-plyakin pull request #1
Opened 2021-09-08 08:50 UTC by plyakin

2021-09-08 08:50 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2021-09-09 10:25 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-09 10:27 UTC, SinimaWath requested changes

2021-09-09 10:27 UTC, SinimaWath commented on 1-module/2-task/index.js
> +    return false;
Обычно малое количество правил(меньше 4), можно лаконично уместить в return:
`return name && name.lenght > 3 ....`

Это как раз тот случай

2021-09-09 10:27 UTC, SinimaWath commented on 1-module/3-task/index.js
> +    if (str.length == 1) return str.toUpperCase();
Давай начнем применять советы из стиля по коду

https://learn.javascript.ru/coding-style#figurnye-skobki

Лучший вариант, он намного лучше читается:
```
if () {

}
```

2021-09-09 10:27 UTC, SinimaWath commented on 1-module/4-task/index.js
> +    let b = 'XXX'.toLowerCase();
Такие переменные-настройки. Принято уносить в глобальную область, нежели чем создавать их каждый раз в функции:
```
  const SPAM_STRING_1 = "1xbet";
  const SPAM_STRING_2 = "xxx";
  
function checkSpam(...


```

2021-09-09 10:27 UTC, SinimaWath commented on 1-module/4-task/index.js
> +    let b = 'XXX'.toLowerCase();
Название переменной не говорящее, другой разработчик не поймет, зачем она нужна:
переменная должна говорить:
- Что она хранит
- Для чего хранит

'a', 'b' - мало о чем говорит

2021-09-09 10:27 UTC, SinimaWath commented on 1-module/4-task/index.js
> +    return false;
Давай без лишнего if, в данной коснтрукции его можно сразу опустить: `return ...`

2021-09-09 10:27 UTC, SinimaWath commented on 1-module/5-task/index.js
> +    if (str.length == maxlength || str.length < maxlength) return str;
Тут тоже советы по стилю кода, давай применим

2021-09-14 20:02 UTC, SinimaWath requested changes

2021-09-14 20:02 UTC, SinimaWath commented on 2-module/2-task/index.js
> +    return false;
Результат операции     ` if (!Object.entries(obj).length)` - уже boolean, поэтому нет необходимости в if, а можно сразу: `return ...`

2021-09-15 19:39 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-16 20:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-16 20:16 UTC, SinimaWath approved these changes

2021-09-16 20:17 UTC, merged